import { test, expect, describe } from "bun:test";
import {
  compressCSV,
  compressJSON,
  compressXML,
  compressHTML,
  compressMarkdown,
  detectContentType,
} from "../src/engine/layer3-media.ts";

describe("Content type detection", () => {
  test("detects JSON", () => {
    expect(detectContentType('{"key": "value"}')).toBe("json");
    expect(detectContentType('[1, 2, 3]')).toBe("json");
  });

  test("detects XML", () => {
    expect(detectContentType('<?xml version="1.0"?>\n<root></root>')).toBe("xml");
  });

  test("detects HTML", () => {
    expect(detectContentType("<html><body>hello</body></html>")).toBe("html");
    expect(detectContentType("<div><p>text</p></div>")).toBe("html");
  });

  test("detects CSV", () => {
    const csv = "name,age,email\nAlice,30,a@b.com\nBob,25,b@c.com\nCharlie,35,c@d.com";
    expect(detectContentType(csv)).toBe("csv");
  });

  test("detects Markdown", () => {
    expect(detectContentType("# Title\n\n- item\n- item")).toBe("markdown");
  });
});

describe("CSV compression", () => {
  test("truncates large CSV", () => {
    const header = "name,age,email";
    const rows = Array.from({ length: 100 }, (_, i) => `user${i},${20 + i},u${i}@test.com`);
    const csv = [header, ...rows].join("\n");

    const result = compressCSV(csv);
    expect(result).toContain("100 rows");
    expect(result).toContain("Schema:");
    expect(result).toContain("First 10 rows");
    expect(result).toContain("90 rows omitted");
    expect(result).not.toContain("user50");
  });

  test("keeps small CSV unchanged", () => {
    const csv = "a,b\n1,2\n3,4";
    expect(compressCSV(csv)).toBe(csv);
  });
});

describe("JSON compression", () => {
  test("minifies pretty-printed JSON", () => {
    const json = JSON.stringify({ key: "value", nested: { a: 1 } }, null, 2);
    const result = compressJSON(json);
    expect(result.length).toBeLessThan(json.length);
    expect(JSON.parse(result)).toEqual({ key: "value", nested: { a: 1 } });
  });

  test("compresses large arrays with schema", () => {
    const items = Array.from({ length: 20 }, (_, i) => ({
      id: i,
      name: `item${i}`,
      value: i * 10,
    }));
    const json = JSON.stringify(items);
    const result = compressJSON(json);
    expect(result).toContain("20 items");
    expect(result).toContain("schema");
    expect(result).toContain("more items");
  });
});

describe("XML compression", () => {
  test("strips duplicate namespace declarations", () => {
    const xml = '<root xmlns:foo="http://foo" xmlns:foo="http://foo"><child/></root>';
    const result = compressXML(xml);
    const nsCount = (result.match(/xmlns:foo/g) || []).length;
    expect(nsCount).toBe(1);
  });

  test("strips auto-generated IDs", () => {
    const xml = '<element id="element_12345">content</element>';
    const result = compressXML(xml);
    expect(result).not.toContain('id="element_12345"');
    expect(result).toContain("content");
  });

  test("strips generation comments", () => {
    const xml = "<!-- Generated by Tool v3.2.1 -->\n<root/>";
    const result = compressXML(xml);
    expect(result).not.toContain("Generated by");
  });

  test("strips DOCTYPE", () => {
    const xml = '<!DOCTYPE html PUBLIC "-//W3C//DTD">\n<root/>';
    const result = compressXML(xml);
    expect(result).not.toContain("DOCTYPE");
  });

  test("unwraps simple CDATA", () => {
    const xml = "<text><![CDATA[simple text content]]></text>";
    const result = compressXML(xml);
    expect(result).toContain("simple text content");
    expect(result).not.toContain("CDATA");
  });
});

describe("HTML compression", () => {
  test("strips script tags", () => {
    const html = "<div>content</div><script>alert('x')</script>";
    const result = compressHTML(html);
    expect(result).not.toContain("script");
    expect(result).toContain("content");
  });

  test("strips style tags", () => {
    const html = "<style>.foo { color: red; }</style><div>content</div>";
    const result = compressHTML(html);
    expect(result).not.toContain("style");
    expect(result).toContain("content");
  });

  test("replaces inline SVG with placeholder", () => {
    const html = '<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0 L10 10"/></svg>';
    const result = compressHTML(html);
    expect(result).toContain("<svg>...</svg>");
    expect(result).not.toContain("path");
  });

  test("compresses Tailwind class soup", () => {
    const html = '<div class="px-4 py-2 flex items-center justify-between text-sm bg-gray-100 border-b rounded-lg shadow-md transition duration-200 cursor-pointer">content</div>';
    const result = compressHTML(html);
    expect(result).toContain("flex");
    expect(result).toContain("utility classes");
  });
});

describe("Markdown compression", () => {
  test("strips HTML embedded in markdown", () => {
    const md = "# Title\n<div>wrapper</div>\n\nContent here.";
    const result = compressMarkdown(md);
    expect(result).not.toContain("<div>");
    expect(result).toContain("# Title");
    expect(result).toContain("Content here");
  });

  test("strips link reference definitions", () => {
    const md = "Click [here][link1]\n\n[link1]: https://example.com\n[link2]: https://other.com";
    const result = compressMarkdown(md);
    expect(result).not.toContain("[link1]: https://");
  });
});
