import type { Layer, CompressionConfig } from "../types/index.ts";
import { compressMessage } from "./layer1-message.ts";

// ── Language detection ──
type Language =
  | "python"
  | "yaml"
  | "makefile"
  | "haskell"
  | "javascript"
  | "typescript"
  | "java"
  | "swift"
  | "kotlin"
  | "go"
  | "rust"
  | "c"
  | "cpp"
  | "csharp"
  | "ruby"
  | "php"
  | "shell"
  | "sql"
  | "html"
  | "css"
  | "unknown";

const INDENTATION_SIGNIFICANT: Set<Language> = new Set([
  "python",
  "yaml",
  "makefile",
  "haskell",
]);

const FENCE_LABELS: Record<string, Language> = {
  python: "python", py: "python",
  yaml: "yaml", yml: "yaml",
  makefile: "makefile", make: "makefile",
  haskell: "haskell", hs: "haskell",
  javascript: "javascript", js: "javascript", jsx: "javascript",
  typescript: "typescript", ts: "typescript", tsx: "typescript",
  java: "java",
  swift: "swift",
  kotlin: "kotlin", kt: "kotlin",
  go: "go", golang: "go",
  rust: "rust", rs: "rust",
  c: "c", h: "c",
  cpp: "cpp", "c++": "cpp", cc: "cpp", cxx: "cpp", hpp: "cpp",
  csharp: "csharp", cs: "csharp", "c#": "csharp",
  ruby: "ruby", rb: "ruby",
  php: "php",
  bash: "shell", sh: "shell", zsh: "shell", shell: "shell",
  sql: "sql",
  html: "html", htm: "html",
  css: "css", scss: "css", sass: "css", less: "css",
};

function detectLanguage(fenceLabel: string, code: string): Language {
  // 1. Check fence label
  const label = fenceLabel.trim().toLowerCase().split(/\s/)[0] ?? "";
  if (label && FENCE_LABELS[label]) return FENCE_LABELS[label]!;

  // 2. Syntax pattern fallback
  if (/^\s*def\s+\w+.*:\s*$/m.test(code) || /^\s*import\s+\w+/m.test(code) && /:\s*$/m.test(code))
    return "python";
  if (/^\s*func\s+\w+/m.test(code) && /\bpackage\s+/m.test(code)) return "go";
  if (/^\s*fn\s+\w+/m.test(code) && /\blet\s+mut\b/m.test(code)) return "rust";
  if (/^\s*(?:const|let|var)\s+\w+/m.test(code) && /=>\s*[{(]/m.test(code))
    return "javascript";
  if (/^\s*(?:interface|type)\s+\w+/m.test(code) && /:\s*\w+/m.test(code))
    return "typescript";
  if (/^\s*(?:public|private|protected)\s+(?:static\s+)?(?:void|int|String)/m.test(code))
    return "java";
  if (/^\s*(?:func|class|struct|enum)\s+\w+/m.test(code) && /\bvar\s+\w+\s*:/m.test(code))
    return "swift";
  if (/^\s*\$\s+/m.test(code) || /^\s*#!\s*\/(?:usr\/)?bin/m.test(code))
    return "shell";
  if (/^\s*<\w+/m.test(code) && /^\s*<\/\w+>/m.test(code)) return "html";
  if (/^\s*SELECT\b/im.test(code) || /^\s*CREATE\s+TABLE\b/im.test(code)) return "sql";
  if (/^\w+:\s*$/m.test(code) && /^\s+-\s+/m.test(code)) return "yaml";

  return "unknown";
}

// ── Comment stripping ──
interface CommentPattern {
  single: RegExp | null;
  blockOpen: RegExp | null;
  blockClose: RegExp | null;
}

const COMMENT_PATTERNS: Record<string, CommentPattern> = {
  default: {
    single: /^\s*\/\/.*$/gm,
    blockOpen: /\/\*/,
    blockClose: /\*\//,
  },
  python: {
    single: /^\s*#(?!!).*$/gm,
    blockOpen: /"""/,
    blockClose: /"""/,
  },
  ruby: {
    single: /^\s*#.*$/gm,
    blockOpen: /=begin/,
    blockClose: /=end/,
  },
  shell: {
    single: /^\s*#(?!!).*$/gm,
    blockOpen: null,
    blockClose: null,
  },
  html: {
    single: null,
    blockOpen: /<!--/,
    blockClose: /-->/,
  },
  css: {
    single: null,
    blockOpen: /\/\*/,
    blockClose: /\*\//,
  },
  sql: {
    single: /^\s*--.*$/gm,
    blockOpen: /\/\*/,
    blockClose: /\*\//,
  },
  haskell: {
    single: /^\s*--.*$/gm,
    blockOpen: /\{-/,
    blockClose: /-\}/,
  },
};

function getCommentPattern(lang: Language): CommentPattern {
  return COMMENT_PATTERNS[lang] ?? COMMENT_PATTERNS["default"]!;
}

// Detect if a commented line is actual commented-out code vs explanatory comment
function isCommentedOutCode(line: string): boolean {
  // Strip comment prefix
  const stripped = line
    .replace(/^\s*\/\/\s?/, "")
    .replace(/^\s*#\s?/, "")
    .replace(/^\s*--\s?/, "")
    .replace(/^\s*\*\s?/, "")
    .trim();

  if (stripped.length === 0) return false;

  // Looks like code if it has: assignments, function calls, brackets, semicolons
  return /[=;{}()\[\]]/.test(stripped) &&
    !/^(?:TODO|FIXME|HACK|NOTE|BUG|XXX|IMPORTANT|WARNING)\b/i.test(stripped);
}

// Detect copyright/license headers
function isCopyrightHeader(comment: string): boolean {
  return /(?:copyright|license|all rights reserved|generated by|auto-generated|\(c\)\s*\d{4})/i.test(
    comment
  );
}

function stripComments(
  code: string,
  lang: Language,
  tier: string
): string {
  const pattern = getCommentPattern(lang);
  let result = code;

  // Strip block comments
  if (pattern.blockOpen && pattern.blockClose) {
    const blockRe = new RegExp(
      `${pattern.blockOpen.source}[\\s\\S]*?${pattern.blockClose.source}`,
      "g"
    );
    result = result.replace(blockRe, (match) => {
      // Always strip copyright headers
      if (isCopyrightHeader(match)) return "";
      // Strip block comments that are just explanations
      // Keep ones that contain important directives
      if (/\b(?:IMPORTANT|WARNING|CRITICAL|DO NOT|MUST)\b/i.test(match)) {
        // Apply Layer 1 trimming to the comment content
        const { compressed } = compressMessage(
          match.replace(/\/\*|\*\/|<!--|-->|\{-|-\}|"""/g, "").trim(),
          "A"
        );
        return `/* ${compressed} */`;
      }
      return "";
    });
  }

  // Strip single-line comments
  if (pattern.single) {
    result = result.replace(pattern.single, (match) => {
      const trimmed = match.trim();

      // Always strip copyright
      if (isCopyrightHeader(trimmed)) return "";

      // Always strip commented-out code
      if (isCommentedOutCode(trimmed)) return "";

      // Strip TODO/FIXME unless it has useful context
      if (/^(?:\/\/|#|--)\s*(?:TODO|FIXME|HACK|XXX)\b/i.test(trimmed)) return "";

      // Keep important directives but apply Layer 1
      if (/\b(?:IMPORTANT|WARNING|CRITICAL|DO NOT|MUST|NOTE)\b/i.test(trimmed)) {
        const content = trimmed
          .replace(/^(?:\/\/|#|--)\s*/, "")
          .replace(/^(?:NOTE|IMPORTANT|WARNING):\s*/i, "")
          .trim();
        const { compressed } = compressMessage(content, "A");
        const prefix = trimmed.startsWith("#") ? "#" : "//";
        return `${match.match(/^\s*/)?.[0] ?? ""}${prefix} ${compressed}`;
      }

      // At tier A: keep explanatory comments (conservative)
      if (tier === "A") return match;

      // At tier B+: strip explanatory comments (Claude can read the code)
      return "";
    });
  }

  return result;
}

// ── Whitespace normalization ──
function normalizeWhitespace(code: string, lang: Language): string {
  const lines = code.split("\n");
  const result: string[] = [];
  let blankCount = 0;

  for (const line of lines) {
    let trimmedRight: string;
    if (INDENTATION_SIGNIFICANT.has(lang)) {
      // Preserve leading whitespace, trim trailing only
      trimmedRight = line.replace(/\s+$/, "");
    } else {
      // Normalize indentation: convert tabs to 2 spaces, trim trailing
      trimmedRight = line
        .replace(/\t/g, "  ")
        .replace(/\s+$/, "");
    }

    if (trimmedRight.length === 0) {
      blankCount++;
      if (blankCount <= 1) result.push(""); // keep max 1 blank line
    } else {
      blankCount = 0;
      result.push(trimmedRight);
    }
  }

  // Trim leading/trailing blank lines
  while (result.length > 0 && result[0] === "") result.shift();
  while (result.length > 0 && result[result.length - 1] === "") result.pop();

  return result.join("\n");
}

// ── Debug/error log compression ──

// Timestamp patterns
const TIMESTAMP_RE =
  /\d{4}[-/]\d{2}[-/]\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?\s*/g;

// Log level prefixes
const LOG_LEVEL_RE = /\[?(?:DEBUG|INFO|WARN(?:ING)?|ERROR|FATAL|TRACE|VERBOSE)\]?\s*/gi;

// Thread/process IDs
const THREAD_ID_RE = /\[?(?:thread|pid|tid)[- ]?\d+\]?\s*/gi;
const BRACKETED_ID_RE = /\[\d+\]\s*/g;

// Long file paths
const FILE_PATH_RE =
  /(?:\/[\w.-]+){3,}\/(\w+\.\w+)/g;

function compressLogs(text: string): string {
  let result = text;

  // Strip timestamps
  result = result.replace(TIMESTAMP_RE, "");

  // Strip log levels (keep ERROR/WARN, strip INFO/DEBUG)
  result = result.replace(
    /\[?(?:DEBUG|INFO|TRACE|VERBOSE)\]?\s*/gi,
    ""
  );

  // Strip thread/process IDs
  result = result.replace(THREAD_ID_RE, "");
  result = result.replace(BRACKETED_ID_RE, "");

  // Shorten file paths
  result = result.replace(FILE_PATH_RE, "...$1");

  // Collapse repeated log lines
  const lines = result.split("\n");
  const compressed: string[] = [];
  let lastLine = "";
  let repeatCount = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === lastLine && trimmed.length > 0) {
      repeatCount++;
    } else {
      if (repeatCount > 0) {
        compressed.push(`  (repeated ${repeatCount + 1} times)`);
      }
      compressed.push(line);
      lastLine = trimmed;
      repeatCount = 0;
    }
  }
  if (repeatCount > 0) {
    compressed.push(`  (repeated ${repeatCount + 1} times)`);
  }

  return compressed.join("\n");
}

// ── Test output compression ──
function compressTestOutput(text: string): string {
  const lines = text.split("\n");
  const kept: string[] = [];
  let inFailure = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Keep failure lines
    if (
      /(?:✗|✘|FAIL|FAILED|ERROR|×|fail\b)/i.test(trimmed) ||
      /^\s*(?:expect|assert|Error|at\s)/i.test(trimmed)
    ) {
      inFailure = true;
      kept.push(line);
      continue;
    }

    // Keep lines right after failure (stack trace, assertion)
    if (inFailure) {
      if (trimmed.length === 0 || /^(?:✓|✔|PASS|pass\b|ok\b)/i.test(trimmed)) {
        inFailure = false;
      } else {
        kept.push(line);
        continue;
      }
    }

    // Strip passing tests
    if (/(?:✓|✔|PASS|pass\b|ok\b)\s/i.test(trimmed)) continue;

    // Strip test runner boilerplate
    if (/^(?:Running|Test Suites?:|Tests?:|Snapshots?:|Time:|Ran \d)/i.test(trimmed)) continue;
    if (/^\s*$/.test(trimmed)) continue;

    // Keep summary lines
    if (/\d+\s+(?:pass|fail)/i.test(trimmed)) {
      kept.push(line);
      continue;
    }

    // Keep everything else (might be relevant)
    kept.push(line);
  }

  return kept.join("\n");
}

// ── Build output compression ──
function compressBuildOutput(text: string): string {
  const lines = text.split("\n");
  const kept: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    // Strip progress lines
    if (/^(?:Compiling|Building|Linking|Downloading|Installing|Resolving)\s+.*\d+\s*(?:of|\/)\s*\d+/i.test(trimmed)) continue;
    if (/^(?:Downloading|Fetching|Resolving|Installing)\s+.*\.{3}\s*(?:Done\.?)?$/i.test(trimmed)) continue;
    if (/^\[\d+\/\d+\]/i.test(trimmed)) continue;
    if (/^#{1,}\s*$/.test(trimmed)) continue; // progress bars

    // Keep errors and warnings
    if (/(?:error|warning|warn|failed|failure|fatal)[\s:]/i.test(trimmed)) {
      kept.push(line);
      continue;
    }

    // Keep everything else
    kept.push(line);
  }

  return kept.join("\n");
}

// ── Terminal noise ──
const ANSI_RE = /\x1b\[[0-9;]*[a-zA-Z]/g;
const SHELL_PROMPT_RE = /^[\w@.-]+\s*[~$%#>]\s*/gm;
const SHELL_PROMPT_FULL_RE = /^(?:\([\w.-]+\)\s*)?[\w@.-]+(?::[\w~/.]+)?[#$%>]\s*/gm;

function stripTerminalNoise(text: string): string {
  let result = text;
  result = result.replace(ANSI_RE, "");
  result = result.replace(SHELL_PROMPT_FULL_RE, "");
  result = result.replace(SHELL_PROMPT_RE, "");
  return result;
}

// ── Repetitive code detection ──
function compressRepetitiveCode(code: string, lang: Language): string {
  // Split into function/method blocks
  const funcPatterns: Record<string, RegExp> = {
    javascript: /^(?:export\s+)?(?:async\s+)?function\s+\w+/,
    typescript: /^(?:export\s+)?(?:async\s+)?function\s+\w+/,
    python: /^def\s+\w+/,
    java: /^(?:public|private|protected)\s+(?:static\s+)?\w+\s+\w+\s*\(/,
    swift: /^(?:func|class\s+func|static\s+func)\s+\w+/,
    go: /^func\s+(?:\(\w+\s+\*?\w+\)\s+)?\w+/,
    rust: /^(?:pub\s+)?fn\s+\w+/,
  };

  const funcStart = funcPatterns[lang];
  if (!funcStart) return code;

  const lines = code.split("\n");
  const functions: { name: string; body: string; startLine: number }[] = [];
  let currentFunc: { name: string; lines: string[]; startLine: number } | null = null;
  let braceDepth = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (funcStart.test(line.trim()) && braceDepth === 0) {
      if (currentFunc) {
        functions.push({
          name: currentFunc.name,
          body: currentFunc.lines.join("\n"),
          startLine: currentFunc.startLine,
        });
      }
      const nameMatch = line.match(/(?:function|def|func|fn)\s+(\w+)/);
      currentFunc = {
        name: nameMatch?.[1] ?? `func_${i}`,
        lines: [line],
        startLine: i,
      };
    } else if (currentFunc) {
      currentFunc.lines.push(line);
    }

    braceDepth += (line.match(/[{(]/g)?.length ?? 0) - (line.match(/[})]/g)?.length ?? 0);
    if (braceDepth < 0) braceDepth = 0;
  }

  if (currentFunc) {
    functions.push({
      name: currentFunc.name,
      body: currentFunc.lines.join("\n"),
      startLine: currentFunc.startLine,
    });
  }

  // Need 3+ similar functions to compress
  if (functions.length < 3) return code;

  // Normalize function bodies for comparison (strip names, whitespace)
  const normalized = functions.map((f) => ({
    ...f,
    norm: f.body.replace(/\b\w+(?=\s*[({])/g, "X").replace(/\s+/g, " ").trim(),
  }));

  // Group by similar structure
  const groups: Map<string, typeof normalized> = new Map();
  for (const func of normalized) {
    let matched = false;
    for (const [key, group] of groups) {
      // Check similarity: same structure, different names/values
      if (areSimilar(func.norm, key)) {
        group.push(func);
        matched = true;
        break;
      }
    }
    if (!matched) {
      groups.set(func.norm, [func]);
    }
  }

  // Only compress groups of 3+
  let result = code;
  for (const [, group] of groups) {
    if (group.length < 3) continue;

    // Keep first as pattern, summarize the rest
    const pattern = group[0]!;
    const names = group.map((g) => g.name).join(", ");
    const summary = `// ${group.length} similar functions: ${names}\n// Pattern shown below, others follow same structure with different names/values\n${pattern.body}\n// ... ${group.length - 1} more similar functions omitted`;

    // Replace all instances with the summary (replace first occurrence only)
    const firstBody = group[0]!.body;
    const idx = result.indexOf(firstBody);
    if (idx !== -1) {
      // Remove all function bodies in the group
      let temp = result;
      for (let i = group.length - 1; i >= 1; i--) {
        temp = temp.replace(group[i]!.body, "");
      }
      temp = temp.replace(firstBody, summary);
      result = temp;
    }
  }

  return result;
}

function areSimilar(a: string, b: string): boolean {
  if (a.length === 0 || b.length === 0) return false;
  // Allow up to 20% character difference
  const maxLen = Math.max(a.length, b.length);
  const minLen = Math.min(a.length, b.length);
  if (minLen / maxLen < 0.8) return false;

  // Count character-level matches
  let matches = 0;
  const shorter = a.length <= b.length ? a : b;
  const longer = a.length > b.length ? a : b;
  for (let i = 0; i < shorter.length; i++) {
    if (shorter[i] === longer[i]) matches++;
  }
  return matches / longer.length > 0.7;
}

// ── Log/test/build output detection ──
function isLogOutput(text: string): boolean {
  const lines = text.split("\n");
  if (lines.length < 3) return false;
  let logLineCount = 0;
  for (const line of lines) {
    if (TIMESTAMP_RE.test(line) || LOG_LEVEL_RE.test(line) || THREAD_ID_RE.test(line)) {
      logLineCount++;
    }
    // Reset lastIndex for global regexes
    TIMESTAMP_RE.lastIndex = 0;
    LOG_LEVEL_RE.lastIndex = 0;
    THREAD_ID_RE.lastIndex = 0;
  }
  return logLineCount / lines.length > 0.3;
}

function isTestOutput(text: string): boolean {
  return /(?:✓|✗|PASS|FAIL|test\s+suite|expect\(|assert)/im.test(text) &&
    /\d+\s+(?:pass|fail|test)/im.test(text);
}

function isBuildOutput(text: string): boolean {
  return /(?:Compiling|Building|Linking|error:|warning:|\[\d+\/\d+\])/im.test(text);
}

// ── IDE-generated file detection ──
const IDE_FILE_PATTERNS = [
  /\.pbxproj$/i,
  /\.storyboard$/i,
  /\.xib$/i,
  /\.xcscheme$/i,
  /Contents\.json$/i,
  /build\.gradle$/i,
  /AndroidManifest\.xml$/i,
  /\.idea\//i,
  /\.iml$/i,
  /\.meta$/i,
  /Info\.plist$/i,
  /launch\.json$/i,
  /\.vscode\/settings\.json$/i,
];

function isIDEGeneratedContent(text: string): boolean {
  // Detect by content patterns (when no filename available)
  return (
    // pbxproj
    /PBXBuildFile|PBXFileReference|PBXGroup/i.test(text) ||
    // Storyboard/xib
    /\bsceneID\b.*\bstoryboardIdentifier\b/i.test(text) ||
    // Unity meta
    /^fileFormatVersion:\s*\d+\s*\nguid:\s*[a-f0-9]+/m.test(text) ||
    // Auto-generated UUIDs repeated heavily
    (text.match(/[A-F0-9]{24}/g)?.length ?? 0) > 10
  );
}

function compressIDEContent(text: string): string {
  let result = text;

  // Strip auto-generated UUIDs (but keep reference structure)
  result = result.replace(/[A-F0-9]{24,}/g, "«UUID»");

  // Collapse repeated default values
  const lines = result.split("\n");
  const kept: string[] = [];
  const seenPatterns = new Set<string>();

  for (const line of lines) {
    // Normalize for comparison (strip values, keep keys)
    const normalized = line.replace(/=\s*.+$/, "= ...").trim();
    if (seenPatterns.has(normalized) && !/[{}[\]]/.test(line)) continue;
    seenPatterns.add(normalized);
    kept.push(line);
  }

  return kept.join("\n");
}

// ── Main code block processor ──
function processCodeBlock(
  code: string,
  fenceLabel: string,
  config: CompressionConfig
): string {
  const lang = detectLanguage(fenceLabel, code);
  let result = code;

  // 1. Detect output type and handle specially
  if (isLogOutput(result)) {
    return compressLogs(result);
  }
  if (isTestOutput(result)) {
    return compressTestOutput(result);
  }
  if (isBuildOutput(result)) {
    return compressBuildOutput(result);
  }

  // 2. Strip terminal noise
  result = stripTerminalNoise(result);

  // 3. IDE-generated content
  if (isIDEGeneratedContent(result)) {
    result = compressIDEContent(result);
  }

  // 4. Strip comments
  result = stripComments(result, lang, config.tier);

  // 5. Normalize whitespace
  result = normalizeWhitespace(result, lang);

  // 6. Flag potentially unused imports (don't strip — risky)
  result = flagUnusedImports(result, lang);

  // 7. Compress repetitive code (tier B+)
  if (config.tier !== "A") {
    result = compressRepetitiveCode(result, lang);
  }

  return result;
}

// ── Import flagging ──
// Detect imports that may be unused. Flag them, don't strip.
function flagUnusedImports(code: string, lang: Language): string {
  const importPatterns: Record<string, RegExp> = {
    javascript: /^import\s+(?:{([^}]+)}|(\w+))\s+from\s+/gm,
    typescript: /^import\s+(?:type\s+)?(?:{([^}]+)}|(\w+))\s+from\s+/gm,
    python: /^(?:from\s+\S+\s+import\s+(.+)|import\s+(.+))$/gm,
    java: /^import\s+(?:static\s+)?[\w.]+\.(\w+)\s*;$/gm,
    go: /^\s*"[\w/.]+"$/gm,
    swift: /^import\s+(\w+)$/gm,
  };

  const pattern = importPatterns[lang];
  if (!pattern) return code;

  const lines = code.split("\n");
  const importLines: { index: number; names: string[] }[] = [];
  const bodyLines: string[] = [];
  let pastImports = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (!pastImports && pattern.test(line.trim())) {
      // Extract imported names
      const names: string[] = [];
      const match = line.match(/\{([^}]+)\}/);
      if (match) {
        names.push(
          ...match[1]!
            .split(",")
            .map((n) => n.trim().split(/\s+as\s+/).pop()!.trim())
            .filter((n) => n.length > 0)
        );
      } else {
        const defaultMatch = line.match(/import\s+(\w+)/);
        if (defaultMatch) names.push(defaultMatch[1]!);
      }
      importLines.push({ index: i, names });
      pattern.lastIndex = 0;
    } else {
      pastImports = true;
      bodyLines.push(line);
    }
  }

  if (importLines.length < 5) return code; // not worth flagging for few imports

  const body = bodyLines.join("\n");
  let flagged = 0;

  for (const imp of importLines) {
    for (const name of imp.names) {
      if (name.length > 1 && !body.includes(name)) {
        // Flag as potentially unused (comment, don't strip)
        lines[imp.index] = `${lines[imp.index]} // ⚠ possibly unused`;
        flagged++;
        break;
      }
    }
  }

  return flagged > 0 ? lines.join("\n") : code;
}

// ── Extract and process code blocks ──
const CODE_BLOCK_RE = /```(\w*)\n([\s\S]*?)```/g;
const INDENTED_BLOCK_RE = /(?:^(?:    |\t).+\n?){3,}/gm;

export function processCodeBlocks(
  text: string,
  config: CompressionConfig
): string {
  let result = text;

  // Process fenced code blocks
  result = result.replace(CODE_BLOCK_RE, (match, label: string, code: string) => {
    const processed = processCodeBlock(code, label, config);
    // Ensure trailing newline before closing fence
    const body = processed.endsWith("\n") ? processed : processed + "\n";
    return `\`\`\`${label}\n${body}\`\`\``;
  });

  // Process indented code blocks (4 spaces or tab)
  result = result.replace(INDENTED_BLOCK_RE, (match) => {
    // Only process if it looks like code, not just indented text
    if (/[=;{}()\[\]<>]/.test(match)) {
      const processed = processCodeBlock(match, "", config);
      return processed;
    }
    return match;
  });

  return result;
}

// ── Layer interface ──
export const layer2: Layer = {
  name: "code-compressor",
  process(text: string, config: CompressionConfig): string {
    if (!config.codeBlocks) return text;
    return processCodeBlocks(text, config);
  },
};

// Export for testing
export { detectLanguage, stripComments, compressLogs, compressTestOutput, compressBuildOutput, stripTerminalNoise, isIDEGeneratedContent };
